In [1]:
import numpy as np

In [4]:
#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3,3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix = np.random.randint(1, 10, size=(5, 5))
print(matrix)

[[4 2 1 1 6]
 [8 7 1 7 1]
 [9 2 3 1 4]
 [1 9 6 2 2]
 [2 2 4 6 8]]


In [7]:
#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix = np.random.randint(0, 1, size=(4, 4))
print(matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, 5)
print(a+b)
print(a-b)
print(a*b)

[15 12  6  6  3]
[1 6 0 4 3]
[56 27  9  5  0]


In [11]:
#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.random(7)
b = np.random.random(7)
print(np.dot(a, b))

1.6465598713304541


In [14]:
#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 3))
print(np.dot(a, b))

[[33 39 42]
 [61 75 74]]


In [15]:
#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a = np.random.randint(0, 10, size=(3, 3))
print(np.linalg.inv(a))

[[-0.12962963  0.16666667  0.25925926]
 [ 0.11111111  0.         -0.22222222]
 [ 0.08641975 -0.11111111  0.16049383]]


In [16]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.randint(0, 10, size=(4, 4))
print(a.T)

[[2 4 0 3]
 [4 6 5 9]
 [0 8 8 0]
 [9 8 7 0]]


In [17]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a = np.random.randint(0, 10, size=(3, 4))
b = np.random.randint(0, 10, 4)
print(a*b)

[[54 20 48 10]
 [18 35 16 45]
 [48 40 56 35]]


In [18]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.randint(0, 1, size=(2, 3))
b = np.random.randint(0, 1, 3)
print(a*b)

[[0 0 0]
 [0 0 0]]


In [6]:
#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 2))
print(a)
print(b)
print(np.dot(a, b))

[[2 0]
 [1 4]]
[[8 0]
 [7 9]]
[[16  0]
 [36 36]]


In [7]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 2))
print(a * b)

[[ 7  0]
 [ 0 56]]


In [11]:
#14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a = np.random.randint(0, 100, size=(5, 5))
print(a)
print(a.sum())

[[40 31 33 29 57]
 [61 28 54 46 67]
 [37 34 14 96 49]
 [ 6 91 30 71 44]
 [93 87 14 42 58]]
1212


In [12]:
#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a = np.random.randint(0, 10, size=(4, 4))
b = np.random.randint(0, 10, size=(4, 4))
print(a - b)

[[ 0 -2  5 -6]
 [-4  1  2  6]
 [-1  5 -2 -2]
 [-2 -5  2 -1]]


In [5]:
#16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a = np.random.randint(0, 2, size=(3, 3), dtype=int)
print(a)
b = np.sum(a, axis=0)
print(np.reshape(b, (-1, 1)))

[[1 1 1]
 [0 0 1]
 [0 0 0]]
[[1]
 [1]
 [2]]


In [32]:
#17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a = np.random.randint(1, 10, size=(3, 4), dtype=int)
print(a)
print(a * a)

[[3 1 4 6]
 [3 6 7 4]
 [4 2 6 7]]
[[ 9  1 16 36]
 [ 9 36 49 16]
 [16  4 36 49]]


In [36]:
#18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a = np.array([4, 9, 6, 25], dtype=int)
print(a)
print(np.sqrt(a))

[ 4  9  6 25]
[2.         3.         2.44948974 5.        ]


In [3]:
a = np.random.rand(3, 3)
print(a)

# Обчислення сум елементів кожного рядка матриці
row_sums = a.sum(axis=1)

# Перетворення одновимірного масиву на вектор-стовпчик
col_vec = row_sums.reshape((-1, 1))

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(col_vec)

[[0.9820638  0.18391386 0.38125471]
 [0.90132196 0.35995848 0.33534451]
 [0.51603624 0.55247594 0.98754099]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[1.54723237]
 [1.59662495]
 [2.05605317]]
